# Generated by Django 3.2.7 on 2021-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.TextField(max_length=500),
        ),
    ]
